config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # ゲストログイン用
    devise_scope :user do
      post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  #ユーザー側
    root to: 'public/homes#top'
    get '/about' => 'public/homes#about'
    get '/search', to: 'public/searches#search'

    scope module: :public do

      get 'users/:id/confirm' => 'users#confirm', as: 'confirm'
      patch 'users/:id/resign' => 'users#resign', as: 'resign'
      get 'users/favorites' => 'users#favorites', as: 'favorites'
      resources :users, only: [:show, :edit, :update]

      resources :posts, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
      end

    end

  # 管理者側
    namespace :admin do
      get 'homes/top'
      resources :users, only: [:show, :edit, :update]
      resources :comments, only: [:index, :destroy]
      resources :posts, only: [:index, :show, :destroy]
    end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :keyword, presence: true
  validates :tag, presence: true, exclusion: { in: %w(---) }


  enum tag: {
    "---":0,
     hokkaido:1,aomnori:2,iwate:3,miyagi:4,akita:5,yamagata:6,fukushima:7,
     ibaraki:8,tochigi:9,gunma:10,saitama:11,chiba:12,tokyo:13,kanagawa:14,
     niigata:15,toyama:16,ishikawa:17,fukui:18,yamanashi:19,nagano:20,
     gifu:21,shizuoka:22,aichi:23,mie:24,
     shiga:25,kyoto:26,osaka:27,hyogo:28,nara:29,wakayama:30,
     tottori:31,shimane:32,okayama:33,hiroshima:34,yamaguchi:35,
     tokushima:36,kagawa:37,ehime:38,kochi:39,
     fukuoka:40,saga:41,nagasaki:42,kumamoto:43,oita:44,miyazaki:45,kagoshima:46,
     okinawa:47
  }

  # 並び替え機能用
  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :most_favorited, -> { includes(:favorites).sort_by { |x| x.favorites.includes(:favorites).size }.reverse }
  scope :most_commented, -> { includes(:comments).sort_by { |x| x.comments.includes(:comments).size }.reverse }

  # 検索機能用
  def self.search_for(keyword)
    Post.where('keyword LIKE ? OR title LIKE ?', "%#{keyword}%", "%#{keyword}%")
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.includes(:user).where(users:{is_deleted: false}).page(params[:page]).per(48)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :tag, :keyword, :image)
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container-fluid">
  <div class="row d-flex justify-content-center align-items-end my-3">
    <h2 class="border-bottom border-gray m-0 pr-1">All Posts</h2>
  </div>

  <div class="col-12 d-flex flex-wrap">
    <% @posts.each do |post| %>
    <div class="text-center col-lg-1 col-md-2 col-sm-6">
      <%= link_to admin_post_path(post) do %>
        <% if post.image.present? %>
          <div class="text-center">
            <%= image_tag post.image, class: "mb-2 w-100", style: "aspect-ratio: 1/1;object-fit: cover;" %>
          </div>
        <% else %>
          <div class="text-center">
            <%= image_tag 'noimage.png', class: "mb-2 w-100", style: "aspect-ratio: 1/1;object-fit: cover;" %>
          </div>
        <% end %>
        <strong class="text-dark d-inline-block text-truncate w-100" style="max-width: 100px;font-size: 14px;"><%= post.title %></strong>
      <% end %>
      <p class="text-dark text-truncate w-100" style="max-width: 100px;font-size: 12px;"><%= post.user.name %></p>
    </div>
      <% end %>
  </div>
  <div class="row justify-content-center">
    <%= paginate @posts, theme: 'twitter-bootstrap-4' %>
  </div>
</div>

app/views/admin/posts/show.html.erb
<div class="container">
  <div class="row justify-content-center mt-3 mb-3">
    <h2 class="border-bottom border-gray">投稿詳細</h2>
  </div>

  <div class="row">
    <div class="col-lg-3 col-sm-12">
      <h2 class="text-center-align mb-4">Posted by</h2>
      <%= render 'public/users/show', user: @user %>
      <div class="text-center-align my-3">
        <%= link_to "このユーザーの他の投稿を確認", admin_user_path(@user), class: "btn btn-outline-success" %>
      </div>
    </div>

    <div class="col-lg-3 col-sm-12">
      <div class="row justify-content-center mt-4">
      <% if @post.image.present? %>
        <%= image_tag @post.image, size: '250x250' %><br>
      <% else %>
        <%= image_tag 'noimage.png' , size: '250x250' %><br>
      <% end %>
      </div>

      <div class="row justify-content-center">
        <p>コメント数：<%= @post.comments.where.not(user_id:User.where(is_deleted:true).pluck(:id)).count %>件</p>
      </div>
    </div>

    <div class="col-lg-6 col-sm-12">
      <%= render 'public/posts/show', post: @post %>

        <div class="mb-4">
          <h5 class="text-center-align">【コメント一覧】</h5>
          <% @post.comments.where.not(user_id:User.where(is_deleted:true).pluck(:id)).each do |comment| %><br>
            <% if comment.user.profile_image.present? %>
              <%= image_tag comment.user.profile_image, size: '50x50', style: 'border-radius:50%' %>&emsp;
            <% else %>
              <%= image_tag 'noimage.png' , size: '50x50', style: 'border-radius:50%' %>&emsp;
            <% end %>
            <strong><%= comment.user.name %></strong>&emsp;
            <%= comment.comment %>&emsp;
            <font size="1"><%= l comment.created_at %></font>&emsp;
            <%= link_to "コメントを削除", admin_comment_path(comment), method: :delete, class: "btn btn-outline-danger btn-sm" %>&emsp;
          <% end %>
        </div>

        <div class="row justify-content-center mb-3">
          <%= link_to "投稿を削除", admin_post_path(@post.id), class: "btn btn-outline-danger", method: :delete, "data-confirm" => "本当に削除しますか？" %>
        </div>
    </div>
  </div>
</div>