config/routes.rb
Rails.application.routes.draw do

  devise_for :users,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
  }

  # ゲストログイン用
    devise_scope :user do
      post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
    end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }

  #ユーザー側
    root to: 'public/homes#top'
    get '/about' => 'public/homes#about'
    get '/search', to: 'public/searches#search'

    scope module: :public do

      get 'users/:id/confirm' => 'users#confirm', as: 'confirm'
      patch 'users/:id/resign' => 'users#resign', as: 'resign'
      get 'users/favorites' => 'users#favorites', as: 'favorites'
      resources :users, only: [:show, :edit, :update]

      resources :posts, only: [:index, :new, :show, :edit, :create, :update, :destroy] do
        resource :favorites, only: [:create, :destroy]
        resources :comments, only: [:create, :destroy]
      end

    end

  # 管理者側
    namespace :admin do
      get 'homes/top'
      resources :users, only: [:show, :edit, :update]
      resources :comments, only: [:index, :destroy]
      resources :posts, only: [:index, :show, :destroy]
    end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true

# 最新のコメントから表示させる用
  scope :latest, -> { order(created_at: :desc) }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :keyword, presence: true
  validates :tag, presence: true, exclusion: { in: %w(---) }


  enum tag: {
    "---":0,
     hokkaido:1,aomnori:2,iwate:3,miyagi:4,akita:5,yamagata:6,fukushima:7,
     ibaraki:8,tochigi:9,gunma:10,saitama:11,chiba:12,tokyo:13,kanagawa:14,
     niigata:15,toyama:16,ishikawa:17,fukui:18,yamanashi:19,nagano:20,
     gifu:21,shizuoka:22,aichi:23,mie:24,
     shiga:25,kyoto:26,osaka:27,hyogo:28,nara:29,wakayama:30,
     tottori:31,shimane:32,okayama:33,hiroshima:34,yamaguchi:35,
     tokushima:36,kagawa:37,ehime:38,kochi:39,
     fukuoka:40,saga:41,nagasaki:42,kumamoto:43,oita:44,miyazaki:45,kagoshima:46,
     okinawa:47
  }

  # 並び替え機能用
  scope :latest, -> { order(created_at: :desc) }
  scope :old, -> { order(created_at: :asc) }
  scope :most_favorited, -> { includes(:favorites).sort_by { |x| x.favorites.includes(:favorites).size }.reverse }
  scope :most_commented, -> { includes(:comments).sort_by { |x| x.comments.includes(:comments).size }.reverse }

  # 検索機能用
  def self.search_for(keyword)
    Post.where('keyword LIKE ? OR title LIKE ?', "%#{keyword}%", "%#{keyword}%")
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true
  validates :introduction, length: { maximum: 50 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # ゲストログイン用
  def self.guest
    find_or_create_by!(name: 'guest' ,email: 'guest@user') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
before_action :authenticate_admin!

  def index
     @comments = Comment.includes(:user).where(users:{is_deleted: false}).page(params[:page]).per(15).latest
  end

  def destroy
    comment = Comment.find(params[:id])
    post_id = comment.post_id
    comment.destroy
    redirect_to admin_post_path(post_id)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
before_action :authenticate_admin!

  def top
    @users = User.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.includes(:user).where(users:{is_deleted: false}).page(params[:page]).per(48)
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :tag, :keyword, :image)
    end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected
  def after_sign_in_path_for(resource)
    admin_homes_top_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
before_action :authenticate_admin!

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).per(8)
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to admin_user_path(@user)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer class=" text-white pt-4 pb-4" style="background-color: #9eceff;">
  <div class="container justify-content-center">
    <div class="text-center">
      <h6>Find your destination!</h6>
      <%= image_tag 'logo.png' , size: '50x50' %>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #9eceff;">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag 'logo.png' , size: '80x80' %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

      <% if admin_signed_in? %> <!--adminログイン状態の際に、表示したいheaderのメニューを記載-->
      <li>
      <%= link_to admin_homes_top_path,class: 'nav-link text-secondary' do %>
      <i class="fas fa-users"></i></i> ユーザー一覧
      <% end %>
      </li>

      <li>
      <%= link_to admin_posts_path,class: 'nav-link text-secondary' do %>
      <i class="fas fa-comments"></i> 投稿一覧
      <% end %>
      </li>

      <li>
      <%= link_to admin_comments_path,class: 'nav-link text-secondary' do %>
      <i class="fas fa-images"></i> コメント一覧
      <% end %>
      </li>

      <li>
      <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-secondary' do %>
      <i class="fas fa-sign-out-alt"></i> ログアウト
      <% end %>
      </li>


      <% elsif user_signed_in? %> <!--userログイン状態の際に、表示したいheaderのメニューを記載-->
      <li>
      <%= link_to user_path(current_user), class:"btn btn-warning" do %>
      <i class="fas fa-user"></i> My page
      <% end %>
      </li>

      <li>
      <%= link_to new_post_path, class:"btn btn-warning" do %>
      <i class="fas fa-plus-square"></i> New Post
      <% end %>
      </li>

      <li>
      <%= link_to posts_path, class:"btn btn-warning" do %>
      <i class="fas fa-images"></i> All Posts
      <% end %>
      </li>

      <li>
      <%= link_to destroy_user_session_path, method: :delete, class:"btn btn-warning" do %>
      <i class="fas fa-sign-out-alt"></i> Sign out
      <% end %>
      </li>


      <% else %> <!--adminでもuserでもログインしていない時に表示するheaderのメニューを記載-->

      <li>
      <%= link_to about_path, class:"btn btn-warning" do %>
      <i class="fas fa-home"></i> About
      <% end %>
      </li>

      <li>
      <%= link_to posts_path, class:"btn btn-warning" do %>
      <i class="fas fa-images"></i> All Posts
      <% end %>
      </li>

      <li>
      <%= link_to new_user_registration_path, class:"btn btn-warning" do %>
      <i class="fas fa-user-plus"></i> Sign up
      <% end %>
      </li>

      <li>
      <%= link_to new_user_session_path, class:"btn btn-warning" do %>
      <i class="fas fa-sign-in-alt"></i> Sign in
      <% end %>
      </li>

      <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VacationMatch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <script src="https://kit.fontawesome.com/b01fce15c4.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--ScrollReveal用-->
    <script src="https://unpkg.com/scrollreveal"></script>
    <!--Googleフォント用-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Merriweather&display=swap" rel="stylesheet">
  </head>

  <header>
    <%= render 'layouts/header' %>
  </header>

  <body style="background-color: #d1e8ff;">
    <%= yield %>
  </body>

  <footer>
    <%= render 'layouts/footer' %>
  </footer>

</html>